name: Deploy Frontend to the Staging Environment

run-name: ${{ github.actor }} has triggered a DEV deployment
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  deploy-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with: 
          node-version: '18'
      - run: |
          npm i         #   add linting, testing, and typechecking next
          npm run build-dev
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Deploy static site to S3 bucket
        run: aws s3 sync ./dist/ ${{ env.ASSET_BUCKET }} --delete
      - name: Invalidate CDN cache
        run: | 
          aws cloudfront create-invalidation --distribution-id ${{ env.CDN_DISTRIBUTION_ID }} --paths "/*"